#!/usr/bin/env python3
"""Static audit of luci-theme-footstrap CSS/JS.

The CSS source is the styles/ tree (one directory per cascade layer); cascade.css
is generated by build-css.sh and is not read here (see docs/17).

Reports:
  1. Bracket balance for every CSS source file and all *.js.
  2. CSS custom properties used via var() but never defined (broken refs) —
     these silently drop the declaration (missing shadows/colors).
  3. Hardcoded color literals in styles/base/*.css that bypass the token bridge —
     un-themed spots a palette switch cannot reach.
  4. !important outside the files allowed to carry it. Every remaining flag
     fights an inline style= attribute or carries a widget's internal layout; a
     new one anywhere else means a rule belongs in a later cascade layer.
  5. Declarations shadowed inside a layer: the same selector, in the same layer
     and the same at-rule context, setting the same property twice. The earlier
     one is dead. Reported only for `theme` and `page`, where it always means a
     rule was appended instead of edited; `base` re-states properties on purpose
     (the reset sets `input { font-size: 100% }`, forms then sets 13px).
  6. Base declarations dead across layers: `theme`/`page` beat `base` regardless
     of specificity, so a base declaration whose selector is repainted on the
     same property by a later layer can never apply. Split in two, and the split
     is the whole point:
       SAFE    — EVERY selector of the base rule is repainted. Coverage is
                 unchanged by deleting it (the same selectors stay themed, just
                 from a later layer), so it is a dead byte. Counted as a finding.
       BACKLOG — only SOME selectors of the group are repainted. NOT a finding
                 and NOT deletable: base groups upstream widgets together
                 (`.cbi-button-positive, .cbi-button-fieldadd, .cbi-button-add`),
                 and dropping the rule would un-theme the members no shipped LuCI
                 page happens to render — which third-party luci-app-* packages
                 DO render. This is the absorption backlog, printed so it can be
                 absorbed into `theme` deliberately, never deleted.

No dependencies. Run from repo root:
  .claude/tooling/preview-venv/bin/python .claude/skills/footstrap-audit/audit.py
  (any python3 works; venv just guarantees one exists)

For behavioural checks (did a change alter any computed style?) use cssdiff.py
in this same directory — a static audit cannot see the cascade.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[3] / "luci-theme-footstrap"
STYLES = ROOT / "styles"
BASE = STYLES / "base"
# the only files allowed an !important. In 90-responsive/20-overview the flags
# outrank an inline style= attribute written by luci-mod-status (29_ports.js) or
# ui.js, which no cascade layer can do. In styles/base they carry widget-internal
# layout (.cbi-dropdown) or a forcing utility (.left/.right/.center).
# 95-a11y-media.css is the third kind: !important INVERTS the layer order, so
# it is the only way one rule can stop animations declared in base as well as in
# theme. That is the canonical form of the media query and it stays.
BANG_OK = ({"90-responsive.css", "20-overview.css", "95-a11y-media.css"}
           | {p.name for p in (STYLES / "base").glob("*.css")})

# vars set at runtime (inline style / other files) — legitimately "undefined" here.
# --zone-color-rgb is written inline on a zone badge by luci-mod-network; it is the
# only --*-rgb left, and the only one that may exist: the theme's own RGB bridge
# (--accent-rgb &c.) was removed for the same reason the HSL one was — see 02-tokens.
VAR_ALLOW = {"--zone-color-rgb", "--on-color"}

def _strip_for_balance(s):
    """Drop comments and quoted strings before counting brackets.

    Counting them raw makes this check punish the very thing the project asks for:
    a dense comment explaining a hazard ("`(` IS on the allow-list") carries a lone
    paren, and the file gets reported as unbalanced while every real parser accepts
    it. The bracket counter is a smoke test for a truncated file, and a truncated
    file is still obvious once comments and strings are gone.

    Regex literals are NOT handled — an unbalanced bracket inside one would still
    fool this. That is acceptable: eslint parses the JS for real in CI, so this is
    the cheap no-dependency backstop, not the authority.
    """
    out, i, n = [], 0, len(s)
    while i < n:
        c = s[i]
        if c == "/" and i + 1 < n and s[i + 1] == "*":          # /* block comment */
            j = s.find("*/", i + 2)
            i = n if j < 0 else j + 2
            continue
        if c == "/" and i + 1 < n and s[i + 1] == "/":          # // line comment
            j = s.find("\n", i)
            i = n if j < 0 else j
            continue
        if c in "\"'`":                                          # quoted string
            q, i = c, i + 1
            while i < n:
                if s[i] == "\\":
                    i += 2
                    continue
                if s[i] == q:
                    i += 1
                    break
                i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)

def balance(path):
    s = _strip_for_balance(path.read_text(encoding="utf-8"))
    bad = [f"{a}{b} {s.count(a)}/{s.count(b)}"
           for a, b in [("{", "}"), ("(", ")"), ("[", "]")] if s.count(a) != s.count(b)]
    return bad

def audit_vars(s):
    # comments first. A comment is free to quote the code it is explaining — the note
    # in 02-tokens.css spells out the removed bridge as `rgba(var(--x), .3)` — and
    # scanning it raw turns that prose into a phantom "used but not defined" var. Same
    # lesson as the bracket counter below: never lex a language out of its comments.
    s = _strip_comments(s)
    defined = set(re.findall(r"(--[a-zA-Z0-9-]+)\s*:", s))
    used = set(re.findall(r"var\((--[a-zA-Z0-9-]+)", s))
    return sorted(u for u in (used - defined) if u not in VAR_ALLOW)

def base_hardcoded(lines):
    sel, out = "", []
    for i, l in enumerate(lines):
        st = l.strip()
        if st.endswith("{"):
            sel = st[:-1].strip()
        if not st.startswith("--") and "--" not in l.split(":")[0]:
            # a real literal = #hex, or a colour function whose first arg is a
            # number (not var()); black/white alpha overlays are ignored.
            after_var = re.sub(r"var\([^()]*\)", "", l)
            lit = re.search(r"#[0-9a-fA-F]{3,8}\b", after_var)
            func = re.search(r"[rh]sla?\(\s*(\d[\d.]*)", after_var)
            if func and re.match(r"(0\s*,\s*0\s*,\s*0|255\s*,\s*255\s*,\s*255)",
                                 after_var[func.start():].split("(", 1)[1].lstrip()):
                func = None
            if lit or func:
                out.append((i + 1, sel[:46], st[:80]))
    return out

# --- rule parsing (enough CSS to spot duplicate selectors; no nesting beyond
# --- @layer / @media / @supports / @container, which is all this tree uses)
def _strip_comments(src):
    out, i = [], 0
    while i < len(src):
        j = src.find("/*", i)
        if j < 0:
            out.append(src[i:]); break
        out.append(src[i:j])
        k = src.find("*/", j + 2)
        if k < 0: break
        i = k + 2
    return "".join(out)

def _split_selectors(head):
    """split on top-level commas only — :is()/:not() may contain their own"""
    out, depth, cur = [], 0, ""
    for ch in head:
        if ch == "(": depth += 1
        elif ch == ")": depth -= 1
        if ch == "," and depth == 0:
            if cur.strip(): out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip(): out.append(cur.strip())
    return out

def rules(path):
    """yield (line, layer, context, selector, [(prop, value)…]) for one file"""
    src = path.read_text(encoding="utf-8")
    s = _strip_comments(src)
    stack, buf, i = [], "", 0
    while i < len(s):
        c = s[i]
        if c == "{":
            head, buf = buf.strip(), ""
            if head.startswith("@"):
                stack.append(head); i += 1; continue
            depth, j = 1, i + 1
            while j < len(s) and depth:
                depth += (s[j] == "{") - (s[j] == "}")
                j += 1
            body, line = s[i + 1:j - 1], s.count("\n", 0, i) + 1
            layer = next((h.split()[1] for h in stack if h.startswith("@layer ")), "")
            ctx = " ".join(h for h in stack if not h.startswith("@layer"))
            if not re.fullmatch(r"[\d.%,\s]+|from|to", head):   # skip @keyframes stops
                decls = []
                for d in body.split(";"):
                    d = d.strip()
                    if d and ":" in d and not d.startswith("--"):
                        prop, val = d.split(":", 1)
                        decls.append((prop.strip(), val.strip()))
                sels = _split_selectors(head)
                for sel in sels:
                    yield line, layer, ctx, sel, decls, len(sels)
            i = j; continue
        if c == "}":
            if stack: stack.pop()
            buf = ""; i += 1; continue
        buf += c; i += 1

def audit_shadowed(css):
    """Same selector + layer + at-rule context, same property set twice: the
    earlier declaration is dead.

    Skipped when the earlier rule carried MORE selectors than the later one.
    That is the group-then-refine idiom — `input…, textarea { min-height: 38px }`
    followed by `textarea { min-height: 84px }` — where the first declaration is
    still doing work for the other members of the group. What we are hunting is
    the opposite: a rule appended at the bottom of the file restating a selector
    already styled above, which is how a stylesheet turns into a changelog."""
    seen, out = {}, []
    for p in css:
        for line, layer, ctx, sel, decls, nsel in rules(p):
            if layer not in ("theme", "page"):
                continue
            for prop, val in decls:
                k = (layer, ctx, sel, prop)
                if k in seen:
                    pf, pl, pv, pn = seen[k]
                    if pn <= nsel:
                        out.append((sel, prop, pf, pl, pv, p.name, line, val))
                seen[k] = (p.name, line, val, nsel)
    return out

def _norm(sel):
    return re.sub(r"\s+", " ", sel).strip()

def audit_base_dead(css):
    """Base declarations that a later layer repaints on an identical selector.

    Layer order (tokens, base, theme, page) means theme/page win over base no
    matter the specificity, so such a base declaration is unreachable. Whether it
    can be DELETED depends on the rest of its selector group, which is the only
    thing this check really exists to get right:

      .cbi-button-positive,      <- theme repaints this one
      .cbi-button-fieldadd,      <- theme does not
      .cbi-button-add,
      .cbi-button-save { border-color: var(--on-color) }

    The declaration is dead for `.cbi-button-positive` and fully alive for the
    other three. Deleting the rule because it "looks overridden" un-themes three
    upstream widgets that no shipped LuCI page renders but a third-party
    luci-app-* does — the coverage contract in CLAUDE.md. So only a group where
    EVERY member is repainted is reported as removable; the mixed ones are
    printed as backlog to absorb, and absorbing means writing the uncovered
    selectors into `theme` first, not deleting them here.
    """
    later = {}
    for p in css:
        for line, layer, ctx, sel, decls, nsel in rules(p):
            if layer in ("theme", "page"):
                later.setdefault((ctx, _norm(sel)), set()).update(pr for pr, _ in decls)

    groups = {}   # one entry per base RULE, keyed by where it starts
    for p in css:
        for line, layer, ctx, sel, decls, nsel in rules(p):
            if layer != "base":
                continue
            g = groups.setdefault((p.name, line, ctx), {"sels": [], "decls": decls})
            g["sels"].append(_norm(sel))

    safe, backlog = [], []
    for (name, line, ctx), g in sorted(groups.items()):
        for prop, val in g["decls"]:
            # an important declaration in base OUTRANKS one in theme (the flag
            # inverts layer order), so it is not dead at all
            if "!important" in val:
                continue
            cov = [prop in later.get((ctx, s), ()) for s in g["sels"]]
            if not cov:
                continue
            if all(cov):
                safe.append((name, line, ", ".join(g["sels"]), prop, val))
            elif any(cov):
                backlog.append((name, line, prop,
                                [s for s, c in zip(g["sels"], cov) if not c]))
    return safe, backlog

def sources():
    """Every source file, in the order build-css.sh concatenates them."""
    return (sorted(STYLES.glob("*.css"))
            + sorted((STYLES / "base").glob("*.css"))
            + sorted((STYLES / "theme").glob("*.css"))
            + sorted((STYLES / "pages").glob("*.css")))

def main():
    if not BASE.is_dir():
        sys.exit(f"not found: {BASE}")
    strict = "--strict" in sys.argv   # CI gate: exit non-zero if anything is reported
    findings = 0
    css = sources()
    s = "\n".join(p.read_text(encoding="utf-8") for p in css)

    # CSS only, deliberately. This used to count brackets in the JS too, and it had to
    # stop: counting them RAW punished dense comments (a lone `(` quoted inside one reads
    # as unbalanced), and counting them after a hand-rolled strip was worse — that
    # stripper read the `//` inside `.replace(/\//g, '.')` as a line comment and ate the
    # rest of the line, which is the exact class of bug this project is guarding against
    # in jsmin. A tool that cannot lex JS has no business counting its brackets.
    # eslint parses the JS for real (CI `lint` job) and tools/jsmin-verify.mjs proves the
    # minified output is token-identical to the source. Those are authorities; this was a
    # guess, and a guess that cried wolf.
    print("== balance (CSS) ==")
    problems = []
    for p in css:
        b = balance(p)
        if b:
            problems.append(p)
            print(f"  BAD {p.relative_to(ROOT)}: {', '.join(b)}")
    findings += len(problems)
    if not problems:
        print("  ok (all balanced)")

    print("\n== css vars used but not defined ==")
    miss = audit_vars(s)
    findings += len(miss)
    print("  none" if not miss else "\n".join(f"  {m}  (x{s.count('var('+m)})" for m in miss))

    print("\n== !important outside the files allowed to carry it ==")
    stray = []
    for p in css:
        if p.name in BANG_OK:
            continue
        for i, l in enumerate(p.read_text(encoding="utf-8").split("\n"), 1):
            # a flag that terminates a declaration; prose in a comment does not
            if re.search(r"!important\s*[;}]", l):
                stray.append((p.name, i, l.strip()[:70]))
    findings += len(stray)
    if not stray:
        print("  none")
    else:
        for name, ln, txt in stray:
            print(f"  {name}:{ln}  {txt}")
        print("  -> move the rule to a later layer, or merge it with its twin")

    print("\n== declarations shadowed within a layer (theme/page) ==")
    sh = audit_shadowed(css)
    findings += len(sh)
    if not sh:
        print("  none")
    else:
        for sel, prop, pf, pl, pv, f, ln, v in sh:
            same = "  SAME VALUE" if pv == v else ""
            print(f"  {sel} {{ {prop} }}  {pf}:{pl} {pv!r} -> {f}:{ln} {v!r}{same}")
        print(f"  ({len(sh)} dead) -> edit the first rule instead of appending a second")
        print("     (group-then-refine, e.g. a shared input rule narrowed for textarea, is not reported)")

    print("\n== base declarations a later layer repaints on the SAME selector ==")
    safe, backlog = audit_base_dead(css)
    findings += len(safe)
    if not safe:
        print("  none removable")
    else:
        for name, ln, sel, prop, val in safe:
            print(f"  {name}:{ln:<4} {sel[:56]}  {{ {prop}: {val[:34]} }}")
        print(f"  ({len(safe)} dead) -> every selector of the rule is repainted by theme/page,")
        print("     so deleting these changes no rendered style (prove it with cssdiff.py)")
    if backlog:
        print(f"\n  -- absorption backlog: {len(backlog)} declaration(s) where only PART of the")
        print("     selector group is repainted. DO NOT DELETE: the members listed below are")
        print("     styled by base alone, and third-party luci-app-* packages emit them.")
        seen_sel = {}
        for name, ln, prop, missing in backlog:
            for m in missing:
                seen_sel.setdefault(m, set()).add(prop)
        for m, props in sorted(seen_sel.items()):
            print(f"       {m[:58]:58} base-only for: {', '.join(sorted(props))[:40]}")

    print("\n== hardcoded colors in styles/base (candidates to tokenize) ==")
    hc = [(p.name, ln, sel, txt)
          for p in sorted(BASE.glob("*.css"))
          for ln, sel, txt in base_hardcoded(p.read_text(encoding="utf-8").split("\n"))]
    findings += len(hc)
    if not hc:
        print("  none")
    else:
        for name, ln, sel, txt in hc:
            print(f"  {name}:{ln:<4} [{sel}] {txt}")
        print(f"  ({len(hc)} lines)")

    print("\nTip: compile-check ucode templates on the router:")
    print("  ssh router 'for f in /usr/share/ucode/luci/template/themes/footstrap*/*.ut; do "
          "ucode -T -c -o /dev/null \"$f\" && echo OK $f || echo FAIL $f; done'")

    # Without --strict this script is a report and always exits 0, which is fine for a
    # human reading it — but useless as a CI gate, which is what it is now also used
    # for. Under --strict, anything at all reported fails the build.
    if strict and findings:
        print(f"\nFAIL: {findings} finding(s) — see above", file=sys.stderr)
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)
